# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aphrodite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aphrodite
  source "https://git.cloud.tencent.com/qcloud_u/cocopoads-repo"
  source "https://github.com/CocoaPods/Specs"
  pod 'TACCore'

end
